local broadcast = require("ludobits.m.broadcast")
local iap_manager = require("iap_manager.iap_manager")

function init(self)
	msg.post(".", "acquire_input_focus")
	
	local products = {
		{
			ident = "android.test.purchased",
			is_consumable = false
		},
	}
	iap_manager.register_products(products)
	iap_manager.init()

	broadcast.register("iap_purchased", function(message, sender)
		if message.ident == "android.test.purchased" then
			gui.set_text(gui.get_node("text_test_product_is_owned"), "Is Owned: True (Purchased)")
		end
	end)

	broadcast.register("iap_restored", function(message, sender)
		if message.ident == "android.test.purchased" then
			gui.set_text(gui.get_node("text_test_product_is_owned"), "Is Owned: True (Restored)")
		end
	end)
	
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if gui.pick_node(gui.get_node("btn_buy_test_iap"), action.x, action.y) and action.released then
		iap_manager.buy("android.test.purchased")
	end
	if gui.pick_node(gui.get_node("btn_reset_all_iap"), action.x, action.y) and action.released then
		iap_manager.force_finish_all()
	end
	if gui.pick_node(gui.get_node("btn_restore_purchases"), action.x, action.y) and action.released then
		iap_manager.restore_owned()
	end	
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end
